%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.26.3

-ifndef(p).
-define(p, true).

-define(p_gpb_version, "3.26.3").

-ifndef('PERSON_PB_H').
-define('PERSON_PB_H', true).
-record('Nick',
        {name                          % = 1, string
        }).
-endif.

-endif.
