%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.26.3
-module(nick).

-export([encode_msg/1, encode_msg/2]).
-export([decode_msg/2, decode_msg/3]).
-export([merge_msgs/2, merge_msgs/3]).
-export([verify_msg/1, verify_msg/2]).
-export([get_msg_defs/0]).
-export([get_msg_names/0]).
-export([get_enum_names/0]).
-export([find_msg_def/1, fetch_msg_def/1]).
-export([find_enum_def/1, fetch_enum_def/1]).
-export([enum_symbol_by_value/2, enum_value_by_symbol/2]).
-export([get_service_names/0]).
-export([get_service_def/1]).
-export([get_rpc_names/1]).
-export([find_rpc_def/2, fetch_rpc_def/2]).
-export([get_package_name/0]).
-export([gpb_version_as_string/0, gpb_version_as_list/0]).

-include("nick.hrl").
-include("gpb.hrl").



-spec encode_msg(_) -> binary().
encode_msg(Msg) -> encode_msg(Msg, []).


-spec encode_msg(_, list()) -> binary().
encode_msg(Msg, Opts) ->
    case proplists:get_bool(verify, Opts) of
      true -> verify_msg(Msg, Opts);
      false -> ok
    end,
    TrUserData = proplists:get_value(user_data, Opts),
    case Msg of
      #'Nick'{} -> e_msg_Nick(Msg, TrUserData)
    end.



e_msg_Nick(Msg, TrUserData) ->
    e_msg_Nick(Msg, <<>>, TrUserData).


e_msg_Nick(#'Nick'{name = F1}, Bin, TrUserData) ->
    begin
      TrF1 = id(F1, TrUserData),
      e_type_string(TrF1, <<Bin/binary, 10>>)
    end.



e_type_string(S, Bin) ->
    Utf8 = unicode:characters_to_binary(S),
    Bin2 = e_varint(byte_size(Utf8), Bin),
    <<Bin2/binary, Utf8/binary>>.

e_varint(N, Bin) when N =< 127 -> <<Bin/binary, N>>;
e_varint(N, Bin) ->
    Bin2 = <<Bin/binary, (N band 127 bor 128)>>,
    e_varint(N bsr 7, Bin2).



decode_msg(Bin, MsgName) when is_binary(Bin) ->
    decode_msg(Bin, MsgName, []).

decode_msg(Bin, MsgName, Opts) when is_binary(Bin) ->
    TrUserData = proplists:get_value(user_data, Opts),
    case MsgName of
      'Nick' -> d_msg_Nick(Bin, TrUserData)
    end.



d_msg_Nick(Bin, TrUserData) ->
    dfp_read_field_def_Nick(Bin, 0, 0,
			    id(undefined, TrUserData), TrUserData).

dfp_read_field_def_Nick(<<10, Rest/binary>>, Z1, Z2, F1,
			TrUserData) ->
    d_field_Nick_name(Rest, Z1, Z2, F1, TrUserData);
dfp_read_field_def_Nick(<<>>, 0, 0, F1, _) ->
    #'Nick'{name = F1};
dfp_read_field_def_Nick(Other, Z1, Z2, F1,
			TrUserData) ->
    dg_read_field_def_Nick(Other, Z1, Z2, F1, TrUserData).

dg_read_field_def_Nick(<<1:1, X:7, Rest/binary>>, N,
		       Acc, F1, TrUserData)
    when N < 32 - 7 ->
    dg_read_field_def_Nick(Rest, N + 7, X bsl N + Acc, F1,
			   TrUserData);
dg_read_field_def_Nick(<<0:1, X:7, Rest/binary>>, N,
		       Acc, F1, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
      10 -> d_field_Nick_name(Rest, 0, 0, F1, TrUserData);
      _ ->
	  case Key band 7 of
	    0 -> skip_varint_Nick(Rest, 0, 0, F1, TrUserData);
	    1 -> skip_64_Nick(Rest, 0, 0, F1, TrUserData);
	    2 ->
		skip_length_delimited_Nick(Rest, 0, 0, F1, TrUserData);
	    5 -> skip_32_Nick(Rest, 0, 0, F1, TrUserData)
	  end
    end;
dg_read_field_def_Nick(<<>>, 0, 0, F1, _) ->
    #'Nick'{name = F1}.

d_field_Nick_name(<<1:1, X:7, Rest/binary>>, N, Acc, F1,
		  TrUserData)
    when N < 57 ->
    d_field_Nick_name(Rest, N + 7, X bsl N + Acc, F1,
		      TrUserData);
d_field_Nick_name(<<0:1, X:7, Rest/binary>>, N, Acc, _,
		  TrUserData) ->
    Len = X bsl N + Acc,
    <<Utf8:Len/binary, Rest2/binary>> = Rest,
    NewFValue = unicode:characters_to_list(Utf8, unicode),
    dfp_read_field_def_Nick(Rest2, 0, 0, NewFValue,
			    TrUserData).


skip_varint_Nick(<<1:1, _:7, Rest/binary>>, Z1, Z2, F1,
		 TrUserData) ->
    skip_varint_Nick(Rest, Z1, Z2, F1, TrUserData);
skip_varint_Nick(<<0:1, _:7, Rest/binary>>, Z1, Z2, F1,
		 TrUserData) ->
    dfp_read_field_def_Nick(Rest, Z1, Z2, F1, TrUserData).


skip_length_delimited_Nick(<<1:1, X:7, Rest/binary>>, N,
			   Acc, F1, TrUserData)
    when N < 57 ->
    skip_length_delimited_Nick(Rest, N + 7, X bsl N + Acc,
			       F1, TrUserData);
skip_length_delimited_Nick(<<0:1, X:7, Rest/binary>>, N,
			   Acc, F1, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_Nick(Rest2, 0, 0, F1, TrUserData).


skip_32_Nick(<<_:32, Rest/binary>>, Z1, Z2, F1,
	     TrUserData) ->
    dfp_read_field_def_Nick(Rest, Z1, Z2, F1, TrUserData).


skip_64_Nick(<<_:64, Rest/binary>>, Z1, Z2, F1,
	     TrUserData) ->
    dfp_read_field_def_Nick(Rest, Z1, Z2, F1, TrUserData).






merge_msgs(Prev, New) -> merge_msgs(Prev, New, []).

merge_msgs(Prev, New, Opts)
    when element(1, Prev) =:= element(1, New) ->
    TrUserData = proplists:get_value(user_data, Opts),
    case Prev of
      #'Nick'{} -> merge_msg_Nick(Prev, New, TrUserData)
    end.

merge_msg_Nick(#'Nick'{}, #'Nick'{name = NFname}, _) ->
    #'Nick'{name = NFname}.



verify_msg(Msg) -> verify_msg(Msg, []).

verify_msg(Msg, Opts) ->
    TrUserData = proplists:get_value(user_data, Opts),
    case Msg of
      #'Nick'{} -> v_msg_Nick(Msg, ['Nick'], TrUserData);
      _ -> mk_type_error(not_a_known_message, Msg, [])
    end.


-dialyzer({nowarn_function,v_msg_Nick/3}).
v_msg_Nick(#'Nick'{name = F1}, Path, _) ->
    v_type_string(F1, [name | Path]), ok.

-dialyzer({nowarn_function,v_type_string/2}).
v_type_string(S, Path) when is_list(S); is_binary(S) ->
    try unicode:characters_to_binary(S) of
      B when is_binary(B) -> ok;
      {error, _, _} ->
	  mk_type_error(bad_unicode_string, S, Path)
    catch
      error:badarg ->
	  mk_type_error(bad_unicode_string, S, Path)
    end;
v_type_string(X, Path) ->
    mk_type_error(bad_unicode_string, X, Path).

-spec mk_type_error(_, _, list()) -> no_return().
mk_type_error(Error, ValueSeen, Path) ->
    Path2 = prettify_path(Path),
    erlang:error({gpb_type_error,
		  {Error, [{value, ValueSeen}, {path, Path2}]}}).


prettify_path([]) -> top_level;
prettify_path(PathR) ->
    list_to_atom(string:join(lists:map(fun atom_to_list/1,
				       lists:reverse(PathR)),
			     ".")).



-compile({inline,id/2}).
id(X, _TrUserData) -> X.




get_msg_defs() ->
    [{{msg, 'Nick'},
      [#field{name = name, fnum = 1, rnum = 2, type = string,
	      occurrence = required, opts = []}]}].


get_msg_names() -> ['Nick'].


get_enum_names() -> [].


fetch_msg_def(MsgName) ->
    case find_msg_def(MsgName) of
      Fs when is_list(Fs) -> Fs;
      error -> erlang:error({no_such_msg, MsgName})
    end.


-spec fetch_enum_def(_) -> no_return().
fetch_enum_def(EnumName) ->
    erlang:error({no_such_enum, EnumName}).


find_msg_def('Nick') ->
    [#field{name = name, fnum = 1, rnum = 2, type = string,
	    occurrence = required, opts = []}];
find_msg_def(_) -> error.


find_enum_def(_) -> error.


-spec enum_symbol_by_value(_, _) -> no_return().
enum_symbol_by_value(E, V) ->
    erlang:error({no_enum_defs, E, V}).


-spec enum_value_by_symbol(_, _) -> no_return().
enum_value_by_symbol(E, V) ->
    erlang:error({no_enum_defs, E, V}).



get_service_names() -> [].


get_service_def(_) -> error.


get_rpc_names(_) -> error.


find_rpc_def(_, _) -> error.



-spec fetch_rpc_def(_, _) -> no_return().
fetch_rpc_def(ServiceName, RpcName) ->
    erlang:error({no_such_rpc, ServiceName, RpcName}).


get_package_name() -> undefined.



gpb_version_as_string() ->
    "3.26.3".

gpb_version_as_list() ->
    [3,26,3].
