%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.26.3

-ifndef(gpb).
-define(gpb, true).

-define(gpb_gpb_version, "3.26.3").

-ifndef('PERSON_PB_H').
-define('PERSON_PB_H', true).
-record('Person',
        {name,                          % = 1, string
         id,                            % = 2, int32
         email                          % = 3, string (optional)
        }).
-endif.

-endif.
