%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.26.3

-ifndef(nick).
-define(nick, true).

-define(nick_gpb_version, "3.26.3").

-ifndef('NICK_PB_H').
-define('NICK_PB_H', true).
-record('Nick',
        {name                           % = 1, string
        }).
-endif.

-endif.
